gaussians:
  initial_num_gaussians: 50
  grad_thr: 1e-5
image:
  path: "./inputs/eye.jpeg"
  height: 128
  width: 128
optim:
  seed: 1
  lr: 0.1
  num_epochs: 1  # gaussians being splitted & pruned each epoch
  num_steps: 2000
  loss:
    name: "diffusion_guidance"
    prompt: "blue eye on red background"
train:
  log_frequency: 50
