gaussians:
  num_gaussians: 10
image:
  path: "./inputs/eye.jpeg"
  height: 128
  width: 128
optim:
  seed: 1
  lr: 0.1
  num_epochs: 1  # gaussians being splitted & pruned each epoch
  num_steps: 200
